<?php
namespace br\gov\saude\esusab\ras\atendindividual;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ExameThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'codigoExame',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'solicitadoAvaliado',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var string
     */
    public $codigoExame = null;
    /**
     * @var string[]
     */
    public $solicitadoAvaliado = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['codigoExame'])) {
                $this->codigoExame = $vals['codigoExame'];
            }
            if (isset($vals['solicitadoAvaliado'])) {
                $this->solicitadoAvaliado = $vals['solicitadoAvaliado'];
            }
        }
    }

    public function getName()
    {
        return 'ExameThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->codigoExame);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->solicitadoAvaliado = array();
                        $_size0 = 0;
                        $_etype3 = 0;
                        $xfer += $input->readListBegin($_etype3, $_size0);
                        for ($_i4 = 0; $_i4 < $_size0; ++$_i4) {
                            $elem5 = null;
                            $xfer += $input->readString($elem5);
                            $this->solicitadoAvaliado []= $elem5;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ExameThrift');
        if ($this->codigoExame !== null) {
            $xfer += $output->writeFieldBegin('codigoExame', TType::STRING, 1);
            $xfer += $output->writeString($this->codigoExame);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->solicitadoAvaliado !== null) {
            if (!is_array($this->solicitadoAvaliado)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('solicitadoAvaliado', TType::LST, 2);
            $output->writeListBegin(TType::STRING, count($this->solicitadoAvaliado));
            foreach ($this->solicitadoAvaliado as $iter6) {
                $xfer += $output->writeString($iter6);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
