<?php
namespace br\gov\saude\esusab\ras\consumoalimentar;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class PerguntaCriancasMenoresSeisMesesEnumThrift
{
    const A_CRIANCA_ONTEM_TOMOU_LEITE_DO_PEITO = 1;

    const MINGAU = 3;

    const AGUA_CHA = 4;

    const LEITE_VACA = 5;

    const FORMULA_INFANTIL = 6;

    const SUCO_FRUTA = 7;

    const FRUTA = 8;

    const COMIDA_DE_SAL = 9;

    const OUTROS_ALIMENTOS_BEBIDAS = 10;

    static public $__names = array(
        1 => 'A_CRIANCA_ONTEM_TOMOU_LEITE_DO_PEITO',
        3 => 'MINGAU',
        4 => 'AGUA_CHA',
        5 => 'LEITE_VACA',
        6 => 'FORMULA_INFANTIL',
        7 => 'SUCO_FRUTA',
        8 => 'FRUTA',
        9 => 'COMIDA_DE_SAL',
        10 => 'OUTROS_ALIMENTOS_BEBIDAS',
    );
}

