<?php
namespace br\gov\saude\esusab\ras\consumoalimentar;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class PerguntaCriancasDeSeisVinteTresMesesEnumThrift
{
    const A_CRIANCA_ONTEM_TOMOU_LEITE_PEITO = 21;

    const ONTEM_A_CRIANCA_COMEU_FRUTA_INTEIRA_PEDACO_AMASSADO = 22;

    const SE_SIM_QUANTAS_VEZES = 23;

    const ONTEM_A_CRIANCA_COMEU_COMIDA_DE_SAL = 24;

    const SE_COMEU_COMIDA_DE_SAL_QUANTAS_VEZES = 25;

    const SE_SIM_ESSA_COMIDA_FOI_OFERECIDA = 26;

    const OUTRO_LEITE_QUE_NAO_LEITE_DO_PEITO = 28;

    const MINGAU_COM_LEITE = 29;

    const IOGURTE = 30;

    const LEGUMES = 31;

    const VEGETAL_OU_FRUTAS_COR_ALARANJADA_OU_FOLHAS_ESCURAS = 32;

    const VERDURA_DE_FOLHA = 33;

    const CARNE = 34;

    const FIGADO = 35;

    const FEIJAO = 36;

    const ARROZ_BATATA_INHAME_MANDIOCA_FARINHA_MACARRAO = 37;

    const HAMBURGUER_E_OU_EMBUTIDOS = 38;

    const BEBIDAS_ADOCADAS = 39;

    const MACARRAO_INSTANTANEO_SALGADINHOS_BISCOITOS = 40;

    const BISCOITO_RECHEADO_DOCES_OU_GULOSEIMAS = 41;

    static public $__names = array(
        21 => 'A_CRIANCA_ONTEM_TOMOU_LEITE_PEITO',
        22 => 'ONTEM_A_CRIANCA_COMEU_FRUTA_INTEIRA_PEDACO_AMASSADO',
        23 => 'SE_SIM_QUANTAS_VEZES',
        24 => 'ONTEM_A_CRIANCA_COMEU_COMIDA_DE_SAL',
        25 => 'SE_COMEU_COMIDA_DE_SAL_QUANTAS_VEZES',
        26 => 'SE_SIM_ESSA_COMIDA_FOI_OFERECIDA',
        28 => 'OUTRO_LEITE_QUE_NAO_LEITE_DO_PEITO',
        29 => 'MINGAU_COM_LEITE',
        30 => 'IOGURTE',
        31 => 'LEGUMES',
        32 => 'VEGETAL_OU_FRUTAS_COR_ALARANJADA_OU_FOLHAS_ESCURAS',
        33 => 'VERDURA_DE_FOLHA',
        34 => 'CARNE',
        35 => 'FIGADO',
        36 => 'FEIJAO',
        37 => 'ARROZ_BATATA_INHAME_MANDIOCA_FARINHA_MACARRAO',
        38 => 'HAMBURGUER_E_OU_EMBUTIDOS',
        39 => 'BEBIDAS_ADOCADAS',
        40 => 'MACARRAO_INSTANTANEO_SALGADINHOS_BISCOITOS',
        41 => 'BISCOITO_RECHEADO_DOCES_OU_GULOSEIMAS',
    );
}

