<?php
namespace br\gov\saude\esusab\dadotransp;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Indica a versão do dado a ser transportado. A versão do dado não necessariamente reflete a versão do sistema.
 */
class VersaoThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'major',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'minor',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'revision',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $major = null;
    /**
     * @var int
     */
    public $minor = null;
    /**
     * @var int
     */
    public $revision = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['major'])) {
                $this->major = $vals['major'];
            }
            if (isset($vals['minor'])) {
                $this->minor = $vals['minor'];
            }
            if (isset($vals['revision'])) {
                $this->revision = $vals['revision'];
            }
        }
    }

    public function getName()
    {
        return 'VersaoThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->major);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->minor);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->revision);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('VersaoThrift');
        if ($this->major !== null) {
            $xfer += $output->writeFieldBegin('major', TType::I32, 1);
            $xfer += $output->writeI32($this->major);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->minor !== null) {
            $xfer += $output->writeFieldBegin('minor', TType::I32, 2);
            $xfer += $output->writeI32($this->minor);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->revision !== null) {
            $xfer += $output->writeFieldBegin('revision', TType::I32, 3);
            $xfer += $output->writeI32($this->revision);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
