<?php
namespace br\gov\saude\esusab\ras\atividadecoletiva;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ProfissionalCboRowItemThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'cnsProfissional',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'codigoCbo2002',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $cnsProfissional = null;
    /**
     * @var string
     */
    public $codigoCbo2002 = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['cnsProfissional'])) {
                $this->cnsProfissional = $vals['cnsProfissional'];
            }
            if (isset($vals['codigoCbo2002'])) {
                $this->codigoCbo2002 = $vals['codigoCbo2002'];
            }
        }
    }

    public function getName()
    {
        return 'ProfissionalCboRowItemThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->cnsProfissional);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->codigoCbo2002);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ProfissionalCboRowItemThrift');
        if ($this->cnsProfissional !== null) {
            $xfer += $output->writeFieldBegin('cnsProfissional', TType::STRING, 1);
            $xfer += $output->writeString($this->cnsProfissional);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->codigoCbo2002 !== null) {
            $xfer += $output->writeFieldBegin('codigoCbo2002', TType::STRING, 2);
            $xfer += $output->writeString($this->codigoCbo2002);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
