<?php
namespace br\gov\saude\esusab\ras\cadastroindividual;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SaidaCidadaoCadastroThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'motivoSaidaCidadao',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'dataObito',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        3 => array(
            'var' => 'numeroDO',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $motivoSaidaCidadao = null;
    /**
     * @var int
     */
    public $dataObito = null;
    /**
     * @var string
     */
    public $numeroDO = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['motivoSaidaCidadao'])) {
                $this->motivoSaidaCidadao = $vals['motivoSaidaCidadao'];
            }
            if (isset($vals['dataObito'])) {
                $this->dataObito = $vals['dataObito'];
            }
            if (isset($vals['numeroDO'])) {
                $this->numeroDO = $vals['numeroDO'];
            }
        }
    }

    public function getName()
    {
        return 'SaidaCidadaoCadastroThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->motivoSaidaCidadao);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->dataObito);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->numeroDO);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SaidaCidadaoCadastroThrift');
        if ($this->motivoSaidaCidadao !== null) {
            $xfer += $output->writeFieldBegin('motivoSaidaCidadao', TType::I64, 1);
            $xfer += $output->writeI64($this->motivoSaidaCidadao);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dataObito !== null) {
            $xfer += $output->writeFieldBegin('dataObito', TType::I64, 2);
            $xfer += $output->writeI64($this->dataObito);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->numeroDO !== null) {
            $xfer += $output->writeFieldBegin('numeroDO', TType::STRING, 3);
            $xfer += $output->writeString($this->numeroDO);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
