<?php
namespace br\gov\saude\esusab\ras\common;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class EncaminhamentoExternoThrift
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'especialidade',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'hipoteseDiagnosticoCid10',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'hipoteseDiagnosticoCiap2',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'classificacaoRisco',
            'isRequired' => false,
            'type' => TType::I64,
        ),
    );

    /**
     * @var int
     */
    public $especialidade = null;
    /**
     * @var string
     */
    public $hipoteseDiagnosticoCid10 = null;
    /**
     * @var string
     */
    public $hipoteseDiagnosticoCiap2 = null;
    /**
     * @var int
     */
    public $classificacaoRisco = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['especialidade'])) {
                $this->especialidade = $vals['especialidade'];
            }
            if (isset($vals['hipoteseDiagnosticoCid10'])) {
                $this->hipoteseDiagnosticoCid10 = $vals['hipoteseDiagnosticoCid10'];
            }
            if (isset($vals['hipoteseDiagnosticoCiap2'])) {
                $this->hipoteseDiagnosticoCiap2 = $vals['hipoteseDiagnosticoCiap2'];
            }
            if (isset($vals['classificacaoRisco'])) {
                $this->classificacaoRisco = $vals['classificacaoRisco'];
            }
        }
    }

    public function getName()
    {
        return 'EncaminhamentoExternoThrift';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->especialidade);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->hipoteseDiagnosticoCid10);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->hipoteseDiagnosticoCiap2);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->classificacaoRisco);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('EncaminhamentoExternoThrift');
        if ($this->especialidade !== null) {
            $xfer += $output->writeFieldBegin('especialidade', TType::I64, 1);
            $xfer += $output->writeI64($this->especialidade);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hipoteseDiagnosticoCid10 !== null) {
            $xfer += $output->writeFieldBegin('hipoteseDiagnosticoCid10', TType::STRING, 2);
            $xfer += $output->writeString($this->hipoteseDiagnosticoCid10);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hipoteseDiagnosticoCiap2 !== null) {
            $xfer += $output->writeFieldBegin('hipoteseDiagnosticoCiap2', TType::STRING, 3);
            $xfer += $output->writeString($this->hipoteseDiagnosticoCiap2);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->classificacaoRisco !== null) {
            $xfer += $output->writeFieldBegin('classificacaoRisco', TType::I64, 4);
            $xfer += $output->writeI64($this->classificacaoRisco);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
