name: Keep thrift updated

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  pull-request-on-thrift-update:
    name: Create pull request if thrift updated

    runs-on: ubuntu-18.04

    container: elaynelemos/thrift:ubuntu-bionic

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Generate updated thrift files
      run: |
         ./bin/update_thrift_files.sh
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
        printf "GitHub Actor: ${GITHUB_ACTOR}\n"
        export BRANCH_FROM="update/thrift-$(date '+%Y-%m-%d')"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git checkout -b "${BRANCH_FROM}" || git checkout "${BRANCH_FROM}"
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add src/cds
        if git diff-index --quiet HEAD --; then
           printf "No changes, leaving.\n"
           exit 0
        else
           printf "Changes found. Pushing branch.\n"
           git commit -m "Automated deployment to update thrift files $(date '+%Y-%m-%d')"
           git push origin "${BRANCH_FROM}"
        fi
        echo "PULL_REQUEST_FROM_BRANCH=${BRANCH_FROM}" >> $GITHUB_ENV
    - name: Open Pull Request
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
